from moscot.problems._base_problem import OTProblem
from moscot.problems._compound_problem import CompoundProblem, MultiCompoundProblem, SingleCompoundProblem
from moscot.problems._multimarginal_problem import MultiMarginalProblem
