codecov:
  require_ci_to_pass: false
  strict_yaml_branch: main

coverage:
  range: 90..100
  status:
    project:
      default:
        target: 1
    patch: off

comment:
  layout: reach, diff, files
  behavior: default
  require_changes: true
  branches:
    - main
