name: Lint

on:
    push:
        branches: [master, dev]
    pull_request:
        branches: [master, dev]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: Set up Python 3.9
            uses: actions/setup-python@v2
            with:
                python-version: 3.9

        -   uses: actions/cache@v2
            with:
                path: ~/.cache/pre-commit
                key: precommit-${{ env.pythonLocation }}-${{ hashFiles('**/.pre-commit-config.yaml') }}

        -   name: Install pip dependencies
            run: |
                python -m pip install --upgrade pip
                pip install tox

        -   name: Lint
            run: |
                tox -e lint
